### ISSUE TITLE
[Question]: cannot import name 'PromptCompressor' from partially initialized module 'llmlingua'

### ISSUE THREAD

**Issue by jiapingW** [microsoft/LLMLingua#173]
### Describe the bug

I pip installed llmlingua in the conda environment. Its version is llmlingua-0.2.2. I created a new python file with the code:
```python
from llmlingua import PromptCompressor
```
It reported an error:
```python
ImportError: cannot import name 'PromptCompressor' from partially initialized module 'llmlingua' (most likely due to a circular import). 
```
I checked your source code and didn't see any obvious circular import problem. Could you tell me how to solve it?

**Comment by iofu728** [comment]
Hi @jiapingW, thanks for your interest in LLMLingua.

Apologies for the late reply. It seems the issue is caused by a local file with the same name as LLMLingua. You can refer to [this Stack Overflow thread](https://stackoverflow.com/questions/64807163/importerror-cannot-import-name-from-partially-initialized-module-m) to resolve the problem.
