### ISSUE TITLE
[Question]: ZeroScrolls reproduction

### ISSUE THREAD

**Issue by cornzz** [microsoft/LLMLingua#186]
### Describe the issue

1. The publicly available validation split only contains a small number of samples (around 20 per task), and the ground truths are not available for the test split, which is a lot bigger. Are the results in the LLMLingua paper obtained from the validation split, or did you submit your results to https://www.zero.scrolls-benchmark.com/submission?

2. The ZeroScrolls dataset provides the inputs already formatted inside the prompt-templates - did you compress the inputs from the dataset as is, or did you extract the contexts from the inputs and compress only the contexts, keeping the prompt templates intact?

**Comment by iofu728** [comment]
Hi @cornzz, thanks for your question, and apologies for the delayed response.

1. In our paper, we used the dev set for ZeroScrolls. Due to the small dataset size, the results are not fully conclusive. However, when compared to the full prompt and other baselines, it does reflect trends across different types of tasks.
2. We manually extracted different sections of the prompt from the original data. You can refer to the following code for details.


```python
TASKS = ['gov_report', 'narrative_qa', 'qasper', 'qmsum', 'summ_screen_fd', 'quality', 'squality', 'musique', 'space_digest', 'book_sum_sort']
OUT_TASKS = ['gov_report', 'summ_screen_fd', 'qmsum', 'squality', 'quality', 'narrative_qa', 'qasper', 'musique', 'space_digest', 'book_sum_sort']
O_QUOTA = [900, 100, 100, 200, 600, 100, 800, 100, 100, 100]
INSTRUCTION_IDX = [2, 1, 1, 1, 1, 1, 1, 1, 1, 1]
QUESTION_IDX = [0, 2, 2, 2, 1, 3, 2, 2, 1, 1]
KEEP_FIRST = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

prompt_sentence = prompt.split("\n\n")
ins_idx, que_ins, keep_first = INSTRUCTION_IDX[task_idx], QUESTION_IDX[task_idx], KEEP_FIRST[task_idx]
ins, prompt, que = "\n\n".join(prompt_sentence[:ins_idx]), "\n\n".join(prompt_sentence[ins_idx:len(prompt_sentence) - que_ins]), "\n\n".join(prompt_sentence[len(prompt_sentence) - que_ins:])
```

**Comment by cornzz** [comment]
Thank you for your response!
